### ISSUE TITLE
Django Dashboard Black PRO - manage.py collectstatic Failed

### ISSUE THREAD

**Issue by app-generator** [app-generator/django-dashboard-black-pro#1]
Action python manage.py collectstatic failed to post process file [nucleo-icons.css](https://github.com/app-generator/priv-django-dashboard-black-pro/blob/master/core/static/assets/css/nucleo-icons.css)

The block that generates the error:

```css
@font-face {
  font-family: 'Nucleo';
  src: url('../fonts/nucleo.eot');
  src: url('../fonts/nucleo.eot') format('embedded-opentype'), 
       url('../fonts/nucleo.woff2') format('woff2'), 
       url('../fonts/nucleo.woff') format('woff'), 
       url('../fonts/nucleo.ttf') format('truetype'), 
       url('../fonts/nucleo.svg') format('svg');
  font-weight: normal;
  font-style: normal;
}
```
Looks like [WhiteNoise](http://whitenoise.evans.io/en/stable/) have issues with relative paths
[Django Dashboard Black PRO](https://appseed.us/admin-dashboards/django-dashboard-dashkit-pro) version - v1.0.0
